

spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bumpworld
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xxx.domain
  configuration:
    map-underscore-to-camel-case: true


server:
  port: 8081

#eureka配置
eureka:
  instance:
    prefer-ip-address: true #上报ip
    ip-address: 127.0.0.1
    instance-id: provider:${server.port}
    lease-expiration-duration-in-seconds: 90 # 服务失效时间 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 30   #续约的间隔时间 服务刷新时间配置，每隔这个时间会主动心跳一次
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka #,http://127.0.0.1:9001/eureka
